
from turtle import Turtle, exitonclick


def f1():
    a = Turtle()
    a.color("green")
    a.fillcolor("black")

    a.pensize(5)
    a.begin_fill()
    a.forward(50)
    a.setheading(45)
    a.forward(25)
    a.setheading(90)
    a.forward(50)
    a.left(45)
    a.forward(25)
    a.left(45)
    a.forward(50)
    a.left(90)
    a.forward(85)
    a.left(90)
    a.end_fill()

    a.forward(30)
    a.penup()
    a.goto(100, 90)
    a.pendown()
    a.forward(30)
    a.right(75)
    a.forward(95)
    a.penup()
    a.goto(100, 90)
    a.pendown()
    a.right(25)
    a.forward(95)
    a.penup()
    a.goto(90, 40)
    a.left(100)
    a.pendown()
    a.forward(55)
def f2():
    n = Turtle()
    n.fillcolor("purple")
    n.pensize(5)
    n.penup()
    n.goto(180, 90)
    n.right(70)
    n.pendown()
    n.begin_fill()
    n.forward(95)
    n.left(70)
    n.forward(25)
    n.left(70)
    n.forward(95)
    n.end_fill()
def f3():
    m = Turtle()
    m.color("blue")
    m.pensize(5)
    m.fillcolor("blue")
    m.penup()
    m.goto(290, 90)
    m.pendown()
    m.forward(70)
    m.goto(330, 90)
    m.right(90)
    m.forward(90)
    m.goto(290, 0)
    m.left(90)
    m.forward(70)
def f4():
    m = Turtle()
    m.color("black")
    m.pensize(5)
    m.fillcolor("red")
    m.penup()
    m.goto(380, 0)
    m.pensize(5)
    m.begin_fill()
    m.pendown()
    m.forward(50)
    m.setheading(45)
    m.forward(25)
    m.setheading(90)
    m.forward(50)
    m.left(45)
    m.forward(25)
    m.left(45)
    m.forward(50)
    m.left(90)
    m.forward(85)
    m.left(90)
    m.end_fill()
def f5():
    b = Turtle()
    b.color("orange")
    b.pensize(15)
    b.fillcolor("yellow")
    b.penup()
    b.goto(0, 170)
    b.begin_fill()
    b.pendown()
    b.setheading(0)
    b.circle(60, 360)
    b.end_fill()

if __name__ == "__main__":
    f1()
    f2()
    f3()
    f4()
    f5()
    exitonclick()
